name: Build Gifs from Python

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: 
          actions/checkout@v4
      -
        name: Install dependencies
        run: bash .github/scripts/install-dependencies.sh
      -
        name: Build gifs
        run: bash .github/scripts/build-videos.sh