name: Build videos from Python

on:
  push:
    branches:
      - main

jobs:
  build:
    environment: Production
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: 
          actions/checkout@v4
      - 
        name: Read version file
        id: dotenv
        uses: falti/dotenv-action@v1.1.4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.DOCKER_REGISTRY }}
          username: ${{ vars.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          build-args: QUALITY=l
          tags: ${{ vars.DOCKER_REGISTRY }}/math-blog-animations:${{ steps.dotenv.outputs.version }}
