name: Build Gifs from Python

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    permissions:
      contents: write
    steps:
      -
        name: Checkout
        uses: 
          actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      -
        name: Install dependencies
        run: bash .github/scripts/install-dependencies.sh
      -
        name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "output/*.mp4"